
airflow:
  executor: "KubernetesExecutor"
  image:
    repository: "airflow-test"
    tag: "latest"
  config:
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    AIRFLOW__KUBERNETES__NAMESPACE: "dev"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "gcr.io/mehdib-airflow-project/drugs-data-pipeline-dev"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "latest"
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"