steps:
# # Build Docker image from Dockerfile
# - name: "gcr.io/cloud-builders/docker"
#   args: ["build", "-t", "${_IMAGE_NAME}", "."]
#   timeout: 200s
# # Push Docker image to Google Cloud Registry  
# - name: "gcr.io/cloud-builders/docker"
#   args: ["push", "${_IMAGE_NAME}"]
#   timeout: 200s
# Execute Unit Tests 
# on built Docker image
- name: "$_IMAGE_NAME:latest"
  # entrypoint: 'bash'
  args: 
    - 'bash -c'
    - '"airflow db init"'
  timeout: 200s

# - name: "gcr.io/cloud-builders/kubectl"
#   args: ["set", "image", "deployment/my-deployment", "my-container=gcr.io/$PROJECT_NAME/$REPO_NAME-$BRANCH_NAME"]
#   env:
#   - "CLOUDSDK_COMPUTE_ZONE=us-east4-b"
#   - "CLOUDSDK_CONTAINER_CLUSTER=my-cluster"
# options:
#     machineType: "N1_HIGHCPU_8"
substitutions:
  _IMAGE_NAME: "gcr.io/${PROJECT_ID}/${REPO_NAME}-${BRANCH_NAME}"

images: ["${_IMAGE_NAME}"]

timeout: 660s

options:
  dynamic_substitutions: true

tags: ["${REPO_NAME}", "${BRANCH_NAME}"]