steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$_IMAGE_TAG", "."]
  timeout: 500s
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "$_IMAGE_TAG"]
# - name: "gcr.io/cloud-builders/kubectl"
#   args: ["set", "image", "deployment/my-deployment", "my-container=gcr.io/$PROJECT_NAME/$REPO_NAME-$BRANCH_NAME"]
#   env:
#   - "CLOUDSDK_COMPUTE_ZONE=us-east4-b"
#   - "CLOUDSDK_CONTAINER_CLUSTER=my-cluster"
# options:
#     machineType: "N1_HIGHCPU_8"
substitutions:
  _IMAGE_TAG: gcr.io/$PROJECT_NAME/$REPO_NAME-$BRANCH_NAME

images: [$_IMAGE_TAG]

timeout: 660s

options:
  dynamic_substitutions: true

tags: ["$REPO_NAME", "$BRANCH_NAME"]